version: 2.1
jobs:
  lint-dockerfile:
    docker:
    - image: public.ecr.aws/docker/library/alpine:latest
    steps:
    - checkout
    - run:
        name: Lint Dockerfile
        command: |
          apk add --no-cache wget
          wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -O /usr/bin/hadolint
          chmod +x /usr/bin/hadolint
          hadolint Dockerfile
  test-app:
    docker:
    - image: public.ecr.aws/docker/library/golang:latest
    working_directory: /go/src/github.com/V4nD3Grac3/a433-microservices/tree/karsajobs
    steps:
    - checkout
    - run:
        name: test backend
        command: |
          apt update
          apt install -y build-essential
          go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
    - image: public.ecr.aws/docker/library/docker:24.0.7-dind
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build and Push Docker Image
        command: |
          set -x
          docker build -t $GH_REPO_BACKEND:$TAG .
          echo $GH_TOKEN | docker login ghcr.io -u $GH_USER --password-stdin
          docker push $GH_REPO_BACKEND:$TAG

workflows:
  version: 2
  lint-test-build:
    jobs:
    - lint-dockerfile
    - test-app:
        requires:
        - lint-dockerfile
    - build-app-karsajobs:
        requires:
        - test-app
    
