version: 2.1

orbs:
    docker: circleci/docker@2.2.0
    go: circleci/go@1.7.3
    
# Define the jobs we want to run for this project
jobs:
  build-app-karsajobs-ui: 
    executor: docker/docker
    environment: 
        IMAGE_NAME: ghcr.io/bagaswinardi/karsajobs-ui
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Docker Image 
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Github Container registry
          command: |
            echo "$CR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows: 
  ci: 
    jobs: 
      - docker/hadolint: 
          dockerfiles: './Dockerfile'
      - build-app-karsajobs-ui: 
          requires: 
            - docker/hadolint