# versi API yang digunakan
apiVersion: v1 
# jenis obyek kubernetes (secret)
kind: Secret
# metadata untuk secret
metadata: 
  # nama metadata 
  name: mongo-credentials
# type data yang akan disimpan dalam secret 
type: Opaque 
data: 
  # data dengn key MONGO_ROOT_USERNAME encode YWRtaW4=
  MONGO_ROOT_USERNAME: YWRtaW4=
  # data dengan key MONGO_ROOT_PASSWORD encode c3VwZXJzZWNyZXRwYXNzd29yZA==
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==